onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mcu_tb/KEY1
add wave -noupdate /mcu_tb/KEY2
add wave -noupdate /mcu_tb/KEY3
add wave -noupdate /mcu_tb/DUT/CPU/ControlBus
add wave -noupdate /mcu_tb/DUT/CPU/AddrBus
add wave -noupdate /mcu_tb/DUT/CPU/DataBus
add wave -noupdate /mcu_tb/DUT/CPU/IR_IF
add wave -noupdate /mcu_tb/DUT/CPU/IR_ID
add wave -noupdate /mcu_tb/DUT/CPU/IR_EX
add wave -noupdate /mcu_tb/DUT/CPU/IR_MEM
add wave -noupdate /mcu_tb/DUT/CPU/IR_WB
add wave -noupdate /mcu_tb/DUT/CPU/EPC
add wave -noupdate /mcu_tb/DUT/CPU/Int_Flush_IF
add wave -noupdate /mcu_tb/DUT/CPU/Int_Flush_ID
add wave -noupdate /mcu_tb/DUT/CPU/Int_Flush_EX
add wave -noupdate /mcu_tb/DUT/CPU/INTA_s
add wave -noupdate /mcu_tb/DUT/CPU/ISR_PC_RD
add wave -noupdate /mcu_tb/DUT/CPU/is_Branch
add wave -noupdate /mcu_tb/DUT/CPU/INTR_Single
add wave -noupdate /mcu_tb/DUT/CPU/PC_HOLD
add wave -noupdate /mcu_tb/DUT/Intr_Controller/IntSrc
add wave -noupdate /mcu_tb/DUT/Intr_Controller/INTR
add wave -noupdate /mcu_tb/DUT/Intr_Controller/INTA
add wave -noupdate /mcu_tb/DUT/Intr_Controller/IRQ_OUT
add wave -noupdate /mcu_tb/DUT/Intr_Controller/INTR_Active
add wave -noupdate /mcu_tb/DUT/Intr_Controller/GIE
add wave -noupdate /mcu_tb/DUT/Intr_Controller/IRQ
add wave -noupdate /mcu_tb/DUT/Intr_Controller/TypeReg
add wave -noupdate /mcu_tb/DUT/Intr_Controller/INTA_Delayed
add wave -noupdate /mcu_tb/DUT/IO_system/CLK
add wave -noupdate /mcu_tb/DUT/IO_system/rst
add wave -noupdate /mcu_tb/DUT/IO_system/MemReadBus
add wave -noupdate /mcu_tb/DUT/IO_system/MemWriteBus
add wave -noupdate /mcu_tb/DUT/IO_system/HEX0
add wave -noupdate /mcu_tb/DUT/IO_system/HEX1
add wave -noupdate /mcu_tb/DUT/IO_system/HEX2
add wave -noupdate /mcu_tb/DUT/IO_system/HEX3
add wave -noupdate /mcu_tb/DUT/IO_system/HEX4
add wave -noupdate /mcu_tb/DUT/IO_system/HEX5
add wave -noupdate /mcu_tb/DUT/IO_system/LEDR
add wave -noupdate /mcu_tb/DUT/IO_system/SWs
add wave -noupdate /mcu_tb/DUT/IO_system/CS_LEDR
add wave -noupdate /mcu_tb/DUT/IO_system/CS_SW
add wave -noupdate /mcu_tb/DUT/IO_system/CS_HEX0_1
add wave -noupdate /mcu_tb/DUT/IO_system/CS_HEX2_3
add wave -noupdate /mcu_tb/DUT/IO_system/CS_HEX4_5
add wave -noupdate /mcu_tb/DUT/IO_system/LEDR_D_Latch
add wave -noupdate /mcu_tb/DUT/IO_system/HEX0_D_Latch
add wave -noupdate /mcu_tb/DUT/IO_system/HEX1_D_Latch
add wave -noupdate /mcu_tb/DUT/IO_system/HEX2_D_Latch
add wave -noupdate /mcu_tb/DUT/IO_system/HEX3_D_Latch
add wave -noupdate /mcu_tb/DUT/IO_system/HEX4_D_Latch
add wave -noupdate /mcu_tb/DUT/IO_system/HEX5_D_Latch
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 258
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {233472 ps}
